import type { Campaign } from './types';

const today = new Date();
const iso = (offsetDays: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().slice(0, 10);
};
const tsAgo = (h: number) => new Date(Date.now() - h * 3600 * 1000).toISOString();

export const MOCK_CAMPAIGNS: Campaign[] = [
  // 1. Growth Audit origin → Live, synced to Asana
  {
    id: 'cmp_001',
    venueId: 'v_gaslamp',
    venueName: 'Gaslamp Tavern',
    origin: 'growth_audit',
    originatingFindingId: 'fnd_soft_shift_001',
    title: 'Tuesday Trivia Revival',
    type: 'Weekly Special',
    status: 'Live',
    startDate: iso(-3),
    endDate: iso(28),
    startTime: '19:00',
    endTime: '22:00',
    description: 'Weekly trivia night with $5 well drinks and half-off appetizers, addressing the Tuesday 7-10pm soft shift.',
    objective: 'Lift Tuesday evening covers by 25%+ over 4 weeks.',
    recurrence: 'Weekly',
    targetAudience: 'Local 25-40 weekday after-work crowd within 2mi.',
    channels: ['Instagram', 'Email', 'In-Venue Signage', 'Google Business Profile'],
    budget: 600,
    expectedGuestCount: 65,
    expectedRevenueImpact: 2400,
    linkedToastPromoCode: 'TRIVIA5',
    linkedMenuItems: ['Loaded Nachos', 'Wings (10pc)', 'House Margarita'],
    successMetric: 'Tuesday net sales 7-11pm',
    assignedTo: 'Maya R.',
    internalNotes: 'Host confirmed for first 4 weeks. Reassess after week 4.',
    attachments: [{ id: 'a1', label: 'Trivia poster.png', kind: 'image' }],
    executionAdapter: {
      adapter_type: 'asana',
      external_id: '120832019283',
      sync_status: 'Synced',
      last_synced_at: tsAgo(2),
    },
    createdAt: tsAgo(120), updatedAt: tsAgo(2),
  },

  // 2. Growth Audit origin → Scheduled, sync failed
  {
    id: 'cmp_002',
    venueId: 'v_north_park',
    venueName: 'North Park Social',
    origin: 'growth_audit',
    originatingFindingId: 'fnd_menu_underpromo_002',
    title: 'Smash Burger Spotlight',
    type: 'Limited-Time Promotion',
    status: 'Scheduled',
    startDate: iso(5),
    endDate: iso(19),
    description: 'Two-week feature push behind the under-ordered Smash Burger (top-3 margin item, bottom-quartile order rate).',
    objective: 'Increase Smash Burger order share from 4% → 10% of entrée mix.',
    recurrence: 'One-Time',
    targetAudience: 'Existing email + IG followers; weekend brunch overflow.',
    channels: ['Instagram', 'TikTok', 'Email', 'Staff Upsell'],
    budget: 350,
    expectedGuestCount: 0,
    expectedRevenueImpact: 1800,
    linkedMenuItems: ['Smash Burger'],
    successMetric: 'Smash Burger units sold / total entrées',
    assignedTo: 'Devon K.',
    attachments: [],
    executionAdapter: {
      adapter_type: 'asana',
      sync_status: 'Sync Failed',
      last_synced_at: tsAgo(8),
      error_message: 'Asana project archived; reassign destination.',
    },
    createdAt: tsAgo(48), updatedAt: tsAgo(8),
  },

  // 3. Manual BarPulse origin → Draft
  {
    id: 'cmp_003',
    venueId: 'v_gaslamp',
    venueName: 'Gaslamp Tavern',
    origin: 'manual_barpulse',
    title: 'Sunday Funday Bottomless Mimosas',
    type: 'Weekly Special',
    status: 'Draft',
    startDate: iso(10),
    endDate: iso(72),
    startTime: '10:00',
    endTime: '14:00',
    description: 'Bottomless mimosas with brunch entrée, Sundays 10am-2pm.',
    objective: 'Establish Sunday brunch as a destination daypart.',
    recurrence: 'Weekly',
    targetAudience: 'Brunch crowd; bachelorette / group bookings.',
    channels: ['Instagram', 'Google Business Profile'],
    budget: 200,
    expectedGuestCount: 80,
    expectedRevenueImpact: 3200,
    linkedToastPromoCode: 'BRUNCH25',
    linkedMenuItems: ['Eggs Benedict', 'Chilaquiles', 'Avocado Toast'],
    successMetric: 'Sunday 10am-2pm covers',
    assignedTo: null,
    attachments: [],
    executionAdapter: { adapter_type: 'asana', sync_status: 'Not Synced' },
    createdAt: tsAgo(20), updatedAt: tsAgo(20),
  },

  // 4. Manual external (created in Asana, ingested) → Live
  {
    id: 'cmp_004',
    venueId: 'v_pb',
    venueName: 'Pacific Beach Public House',
    origin: 'manual_external',
    title: 'Pints for Paws (Animal Shelter Partnership)',
    type: 'Brand Partnership',
    status: 'Live',
    startDate: iso(-1),
    endDate: iso(13),
    description: '$1 per pint donated to local shelter. Pet adoption event on closing weekend.',
    objective: 'Community goodwill + new-guest acquisition via partner audience.',
    recurrence: 'One-Time',
    targetAudience: 'Pet owners 25-55 in coastal SD.',
    channels: ['Instagram', 'Facebook', 'Press', 'In-Venue Signage'],
    brandPartner: 'San Diego Humane Society',
    brandPartnerContribution: 500,
    budget: 400,
    expectedGuestCount: 220,
    expectedRevenueImpact: 5200,
    linkedMenuItems: ['Draft IPA', 'Pilsner', 'Hazy IPA'],
    successMetric: 'Total pints sold + new IG follows',
    assignedTo: 'Rae M.',
    internalNotes: 'Originated in Asana by GM; pulled into BarPulse via adapter.',
    attachments: [],
    executionAdapter: {
      adapter_type: 'asana',
      external_id: '120855501192',
      sync_status: 'Synced',
      last_synced_at: tsAgo(6),
    },
    createdAt: tsAgo(240), updatedAt: tsAgo(6),
  },

  // 5. Manual BarPulse → Approved, awaiting schedule
  {
    id: 'cmp_005',
    venueId: 'v_north_park',
    venueName: 'North Park Social',
    origin: 'manual_barpulse',
    title: 'Holiday Gift Card Boost',
    type: 'Seasonal/Holiday',
    status: 'Approved',
    startDate: iso(20),
    endDate: iso(55),
    description: '$10 bonus card with every $50 gift card purchase, mid-Nov through New Year.',
    objective: 'Drive Q4 cash-flow + Q1 repeat visit base.',
    recurrence: 'One-Time',
    targetAudience: 'Existing guests, holiday shoppers.',
    channels: ['Email', 'SMS', 'Instagram', 'In-Venue Signage'],
    budget: 250,
    expectedRevenueImpact: 7500,
    linkedMenuItems: [],
    successMetric: 'Gift card $ sold',
    assignedTo: 'Devon K.',
    attachments: [],
    executionAdapter: { adapter_type: 'asana', sync_status: 'Not Synced' },
    createdAt: tsAgo(72), updatedAt: tsAgo(36),
  },

  // 6. Growth Audit → Ended with results (winner)
  {
    id: 'cmp_006',
    venueId: 'v_gaslamp',
    venueName: 'Gaslamp Tavern',
    origin: 'growth_audit',
    originatingFindingId: 'fnd_event_lift_004',
    title: 'Padres Home Game Pre-Game Hour',
    type: 'Event',
    status: 'Ended',
    startDate: iso(-30),
    endDate: iso(-2),
    startTime: '16:00',
    endTime: '18:30',
    description: 'Pre-game $4 drafts + $6 stadium dogs, all home games.',
    objective: 'Capture pre-game foot traffic; lift 4-6pm covers on game days.',
    recurrence: 'Custom',
    targetAudience: 'Padres ticket holders walking to Petco.',
    channels: ['Instagram', 'Google Business Profile', 'In-Venue Signage'],
    budget: 800,
    expectedGuestCount: 350,
    expectedRevenueImpact: 8500,
    linkedToastPromoCode: 'PREGAME',
    linkedMenuItems: ['Stadium Dog', 'Draft Lager', 'Wings (6pc)'],
    successMetric: 'Game-day 4-6pm net sales',
    assignedTo: 'Maya R.',
    attachments: [],
    executionAdapter: {
      adapter_type: 'asana', external_id: '120800010034',
      sync_status: 'Synced', last_synced_at: tsAgo(48),
    },
    results: {
      attributedRevenue: 11200,
      redemptions: 412,
      featuredItemUnitsSold: 286,
      actualGuestCount: 438,
      actualVsExpectedDelta: 25,
      laborCost: 1850,
      laborToRevenueRatio: 0.165,
      roi: 12.5,
      confidence: 'High',
      narrativeSummary: 'Outperformed by 25%. Stadium Dog drove 70% of redemptions; bar throughput peaked at 5:15pm. Recommend extending to all home games next season and pre-staging a second bartender.',
      recommendation: 'Repeat',
      finalDecision: 'Scale',
    },
    createdAt: tsAgo(700), updatedAt: tsAgo(24),
  },

  // 7. Manual external → Ended with mediocre results
  {
    id: 'cmp_007',
    venueId: 'v_pb',
    venueName: 'Pacific Beach Public House',
    origin: 'manual_external',
    title: 'Taco Tuesday Influencer Push',
    type: 'Content Push',
    status: 'Ended',
    startDate: iso(-21),
    endDate: iso(-7),
    description: '3 mid-tier local food influencers seeded with comp visits + posting requirement.',
    objective: 'Drive Tuesday taco mix + new-guest count.',
    recurrence: 'One-Time',
    targetAudience: 'IG-active SD foodies 22-35.',
    channels: ['Instagram', 'TikTok', 'Influencer'],
    budget: 1200,
    expectedGuestCount: 150,
    expectedRevenueImpact: 4200,
    linkedMenuItems: ['Carne Asada Taco', 'Al Pastor Taco', 'Baja Fish Taco'],
    successMetric: 'Tuesday taco units + IG saves',
    assignedTo: 'Rae M.',
    attachments: [],
    executionAdapter: {
      adapter_type: 'asana', external_id: '120790004412',
      sync_status: 'Synced', last_synced_at: tsAgo(120),
    },
    results: {
      attributedRevenue: 2700,
      redemptions: 0,
      featuredItemUnitsSold: 178,
      actualGuestCount: 112,
      actualVsExpectedDelta: -25,
      laborCost: 980,
      laborToRevenueRatio: 0.363,
      roi: 1.25,
      confidence: 'Medium',
      narrativeSummary: 'Reach was strong (78k impressions) but conversion underwhelmed. One influencer did not post until day 6. Future runs should require posts on day 1 and concentrate budget on a single high-fit creator.',
      recommendation: 'Tweak',
      finalDecision: 'Improve',
    },
    createdAt: tsAgo(500), updatedAt: tsAgo(120),
  },

  // 8. Growth Audit → Archived
  {
    id: 'cmp_008',
    venueId: 'v_north_park',
    venueName: 'North Park Social',
    origin: 'growth_audit',
    originatingFindingId: 'fnd_local_visibility_010',
    title: 'GBP Karaoke Keyword Push',
    type: 'Other',
    status: 'Archived',
    startDate: iso(-90),
    endDate: iso(-60),
    description: 'GBP attribute updates + 4 weekly photo posts highlighting karaoke nights.',
    objective: 'Rank top-3 for "karaoke bar North Park".',
    recurrence: 'Weekly',
    targetAudience: 'Local search users.',
    channels: ['Google Business Profile'],
    budget: 0,
    expectedRevenueImpact: 0,
    linkedMenuItems: [],
    successMetric: 'Local pack rank for karaoke keywords',
    assignedTo: 'Devon K.',
    attachments: [],
    executionAdapter: { adapter_type: 'asana', sync_status: 'Synced', external_id: '120700000091', last_synced_at: tsAgo(2160) },
    results: {
      attributedRevenue: 0,
      narrativeSummary: 'Reached top-3 for 2 of 3 target queries within 5 weeks. Revenue attribution inconclusive — archived but kept as ongoing reference.',
      confidence: 'Low',
      recommendation: 'Repeat',
      finalDecision: 'Repeat',
    },
    createdAt: tsAgo(2400), updatedAt: tsAgo(2160),
  },

  // 9. Manual BarPulse → Live, recurring
  {
    id: 'cmp_009',
    venueId: 'v_pb',
    venueName: 'Pacific Beach Public House',
    origin: 'manual_barpulse',
    title: 'Industry Night (Mondays)',
    type: 'Happy Hour Variation',
    status: 'Live',
    startDate: iso(-60),
    endDate: iso(120),
    startTime: '21:00',
    endTime: '00:00',
    description: '50% off all drinks for service-industry workers with paystub or badge, Mondays 9pm-close.',
    objective: 'Build a loyal late-Monday base + organic word-of-mouth.',
    recurrence: 'Weekly',
    targetAudience: 'Local restaurant + bar staff.',
    channels: ['Instagram', 'In-Venue Signage', 'Staff Upsell'],
    budget: 0,
    expectedGuestCount: 40,
    expectedRevenueImpact: 1100,
    linkedMenuItems: [],
    successMetric: 'Monday 9pm-close net sales',
    assignedTo: 'Rae M.',
    attachments: [],
    executionAdapter: { adapter_type: 'asana', external_id: '120755500001', sync_status: 'Syncing', last_synced_at: tsAgo(0.1) },
    createdAt: tsAgo(1500), updatedAt: tsAgo(0.1),
  },

  // 10. Manual BarPulse → Scheduled, big event
  {
    id: 'cmp_010',
    venueId: 'v_gaslamp',
    venueName: 'Gaslamp Tavern',
    origin: 'manual_barpulse',
    title: 'NYE Countdown Party',
    type: 'Event',
    status: 'Scheduled',
    startDate: iso(45),
    endDate: iso(45),
    startTime: '20:00',
    endTime: '02:00',
    description: 'Ticketed NYE party: open champagne toast, DJ, late-night menu.',
    objective: 'Sell out 200 tickets at $65; max bar throughput.',
    recurrence: 'One-Time',
    targetAudience: 'Downtown 25-45 NYE crowd.',
    channels: ['Instagram', 'Email', 'Paid Ads', 'Press'],
    budget: 3500,
    expectedGuestCount: 200,
    expectedRevenueImpact: 22000,
    linkedMenuItems: ['Champagne Toast', 'Late Night Slider', 'Truffle Fries'],
    successMetric: 'Tickets sold + bar revenue',
    assignedTo: 'Maya R.',
    attachments: [{ id: 'a2', label: 'NYE flyer v3.png', kind: 'image' }],
    executionAdapter: { adapter_type: 'asana', external_id: '120899900012', sync_status: 'Synced', last_synced_at: tsAgo(12) },
    createdAt: tsAgo(160), updatedAt: tsAgo(12),
  },
];
