import { Link } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Container } from "@/components/marketing/studio/primitives";
import { StudioHeader } from "@/components/marketing/studio/StudioHeader";
import { StudioFooter } from "@/components/marketing/studio/StudioFooter";
import { Inquiry } from "@/components/marketing/studio/sections/Inquiry";
import { ServiceWork } from "@/components/marketing/studio/ServiceWork";
import { useStudioHead } from "@/components/marketing/studio/useStudioHead";
import { trackSiteEvent } from "@/lib/studioAnalytics";
import { ROUTE_META } from "@/config/routeMeta";

const questions = [
  ["Do you write the words too?", "Yes. Messaging and copywriting can be part of the agreed scope."],
  ["Can you work with my existing logo?", "Yes. We can refresh or extend it rather than replacing it without a reason."],
  ["Who owns it?", "You do. Ownership is documented in writing."],
  ["How is it priced?", "The work is scoped and quoted in writing after a short conversation."],
];
const scope = ["Positioning and messaging", "Copywriting", "Naming help", "Logo and identity system", "Typography and color", "Short brand guide", "Signage, print and menus", "Social templates", "Website look"];

export default function BrandServices() {
  useStudioHead({ ...ROUTE_META["/services/brand"], path: "/services/brand" });
  return <div className="stm-studio svc-page brand-page min-h-screen"><StudioHeader/><main>
    <section className="svc-hero svc-band-light" aria-labelledby="brand-title"><Container className="svc-hero-grid"><div className="svc-hero-copy"><span className="home-eyebrow">01 / Brand & creative</span><h1 id="brand-title">Make the quality of your business <em>obvious.</em></h1><p>Positioning, messaging, logo and visual identity, plus the signs, menus, social templates and website pieces that carry it.</p><div className="svc-actions"><a className="home-btn-amber" href="#contact" onClick={() => trackSiteEvent({ event_type: "cta_click", label: "talk_brand" })}>Talk about your brand <ArrowRight size={16} aria-hidden/></a><Link className="home-btn-ghost" to="/work" onClick={() => trackSiteEvent({ event_type: "cta_click", label: "brand_see_work" })}>See the work <ArrowRight size={16} aria-hidden/></Link></div></div><div className="brand-identity" aria-label="The Harbor Room identity spread with business card, menu, type specimen and color palette"><div className="brand-identity-top"><span>THE HARBOR ROOM</span><span>EST. BY THE WATER</span></div><div className="brand-identity-mark">The<br/><i>Harbor</i><br/>Room<span>COASTAL DINING</span></div><div className="brand-identity-strip"><span/><span/><span/><span/></div><div className="brand-identity-type"><small>TYPE / VOICE</small><strong>Good things take time.</strong><i>Stay a while.</i></div><div className="brand-identity-card"><span>THE HARBOR ROOM</span><strong>Come as you are.<br/>Stay for the evening.</strong><small>Coastal dining · San Diego</small></div><div className="brand-identity-menu"><span>THE HARBOR ROOM</span><strong>Tonight’s Menu</strong><hr/><p>To start<br/>From the coast<br/>Something sweet</p><small>GOOD FOOD. LONG EVENINGS.</small></div></div></Container></section>
    <section className="svc-section svc-band-dark brand-system" aria-labelledby="brand-system-title"><Container><span className="home-eyebrow">02 / Message to identity</span><h2 id="brand-system-title" className="home-section-title">One idea, carried <em>all the way through.</em></h2><div className="brand-system-grid"><div><small>POSITIONING</small><p>A neighborhood dining room worth staying for.</p></div><div><small>VOICE</small><p>Come as you are. Stay for the evening.</p></div><div><small>TYPOGRAPHY</small><p className="brand-system-type">The evening is yours.</p></div><div><small>COLOR</small><div className="brand-system-colors"><i/><i/><i/><i/></div></div><div className="brand-system-logo"><small>LOGO LOCKUP</small><strong>The <i>Harbor</i> Room</strong><span>COASTAL DINING</span></div></div></Container></section>
    <section className="svc-section svc-band-light brand-gallery" aria-labelledby="brand-gallery-title"><Container><span className="home-eyebrow">03 / In the world</span><h2 id="brand-gallery-title" className="home-section-title">An identity that <em>shows up.</em></h2><div className="brand-gallery-layout"><div className="brand-sign"><span>THE HARBOR ROOM</span><strong>The <i>Harbor</i><br/> Room</strong><small>COASTAL DINING</small></div><div className="brand-gallery-details"><div className="brand-gallery-print"><span>MENU / PRINT</span><strong>Tonight’s Menu</strong><p>A good evening starts here.</p></div><div className="brand-gallery-social"><span>SOCIAL</span><strong>Pull up a chair.</strong><small>THE HARBOR ROOM</small></div><div className="brand-gallery-web"><span>WEBSITE</span><nav>The Harbor Room <b>Menu &nbsp; Visit</b></nav><strong>Stay a while.</strong></div></div></div></Container></section>
    <ServiceWork type="brand" order={["big-paws-club", "coastal-beauties", "kario-voss"]}/>
    <section className="svc-section svc-band-light brand-engagement" aria-labelledby="brand-engagement-title"><Container><span className="home-eyebrow">05 / Working together</span><h2 id="brand-engagement-title" className="home-section-title">Built to be <em>used.</em></h2><div className="brand-engagement-grid"><div><h3>What we can scope</h3><ul>{scope.map(item => <li key={item}>{item}</li>)}</ul></div><div><h3>What you receive</h3><p>Final files in standard formats, source files, a short brand guide and ownership documented in writing.</p><h3>Review points</h3><ol><li>Direction</li><li>First round</li><li>Refinement</li><li>Final approval</li></ol></div></div><div className="svc-questions"><h3>Questions worth asking.</h3><Accordion type="single" collapsible>{questions.map(([q,a],i) => <AccordionItem key={q} value={`brand-q-${i}`}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></div></Container></section>
    <Inquiry servicePage="brand"/>
  </main><StudioFooter/></div>;
}
