import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import fallback from "./industry-meta.json" with { type: "json" };
import { ROUTE_META } from "../src/config/routeMeta.js";
const SITE="https://supremeteammedia.com",root=resolve("dist"),base=await readFile(resolve(root,"index.html"),"utf8");
let industries=fallback;const url=process.env.VITE_SUPABASE_URL,key=process.env.VITE_SUPABASE_PUBLISHABLE_KEY;if(url&&key){try{const r=await fetch(`${url}/rest/v1/vertical_landing_pages?select=slug,meta_title,meta_description,layout&status=eq.published&page_version=gte.2&order=slug`,{headers:{apikey:key,Authorization:`Bearer ${key}`}});if(!r.ok)throw new Error(String(r.status));industries=(await r.json()).map(x=>({slug:x.slug,title:x.meta_title,description:x.meta_description,mediaKey:x.layout?.hero?.media}));}catch(e){console.warn(`[prerender] using fallback: ${e.message}`)}}
const images={"home-industry-hvac":"/__l5e/assets-v1/02d7382a-189c-4b45-9aa0-7d371635fada/home-industry-hvac.webp","home-industry-pizza":"/__l5e/assets-v1/9222b4e5-bfa5-4056-8c21-4e5f530d8539/home-industry-pizza.webp","home-industry-medspa":"/__l5e/assets-v1/db8f3cb0-527c-4e9b-8ae7-3c04ec183038/home-industry-medspa.webp"};
const routes=Object.entries(ROUTE_META).map(([path,v])=>({path,...v}));industries.forEach(x=>routes.push({path:`/for/${x.slug}`,title:x.title,description:x.description,image:x.mediaKey?images[x.mediaKey]:undefined}));
const cases=[['allmighty-supreme','AllMighty Supreme — Personal brand website','A personal brand and portfolio experience built to present creative work, systems, and professional range in one place.'],['big-paws-club','Big Paws Club — Editorial & lifestyle brand website','A content-rich large-dog brand experience combining practical guides, editorial structure, audience-building paths, and future product and shop experiences.'],['supreme-wellness-club','Supreme Wellness Club — Wellness brand website','A wellness-focused digital experience combining education, guided paths, and a premium lifestyle presentation.'],['barpulse','BarPulse — Hospitality operations platform','A hospitality operating system connecting operational information, management workflows, scorecards, tasks, and AI-assisted insights.'],['kario-voss','Kario Voss — Artist website','A mobile-first artist site bringing music, visuals, press materials, and identity into one focused digital experience.'],['coastal-beauties','Coastal Beauties — Lifestyle & creator-culture website','A Southern California lifestyle and creator-culture destination combining editorial storytelling, brand identity, content, and audience growth.'],['sylina-renae','Sylina Renae — Artist website','A cinematic artist website presenting music, visuals, press materials and identity in one experience.']];cases.forEach(([slug,title,description])=>routes.push({path:`/work/${slug}`,title:`${title} — Supreme Team Media`,description}));
const esc=v=>String(v).replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;"),set=(h,p,r)=>p.test(h)?h.replace(p,r):h.replace("</head>",`  ${r}\n</head>`);
for(const x of routes){const canonical=`${SITE}${x.path==="/"?"/":x.path}`,image=x.image?`${SITE}${x.image}`:`${SITE}/og-home.jpg`;let h=base.replace(/<title>.*?<\/title>/s,`<title>${esc(x.title)}</title>`);h=set(h,/<meta name="description"[^>]*>/,`<meta name="description" content="${esc(x.description)}">`);h=set(h,/<link rel="canonical"[^>]*>/,`<link rel="canonical" href="${canonical}">`);for(const[p,c]of[["og:title",x.title],["og:description",x.description],["og:url",canonical],["og:image",image]])h=set(h,new RegExp(`<meta property="${p}"[^>]*>`),`<meta property="${p}" content="${esc(c)}">`);for(const[n,c]of[["twitter:title",x.title],["twitter:description",x.description],["twitter:image",image]])h=set(h,new RegExp(`<meta name="${n}"[^>]*>`),`<meta name="${n}" content="${esc(c)}">`);const out=x.path==="/"?resolve(root,"index.html"):resolve(root,x.path.slice(1),"index.html");await mkdir(dirname(out),{recursive:true});await writeFile(out,h)}
const manifest=resolve(root,"prerender-routes.json");await writeFile(manifest,JSON.stringify(routes.map(x=>x.path)));const run=spawnSync("python3",[resolve("scripts/prerender-pages.py"),root,manifest],{stdio:"inherit",timeout:240000});await rm(manifest,{force:true});if(run.error||run.status!==0)console.warn("[prerender] page rendering unavailable; metadata SPA fallbacks remain");console.log(`[prerender] prepared ${routes.length} routes`);