
-- Migration 5: New tables Part 1 — Employee system

CREATE TABLE IF NOT EXISTS employee_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID,
  venue_id UUID NOT NULL REFERENCES venues(id),
  employee_name TEXT NOT NULL,
  preferred_name TEXT,
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  phone TEXT,
  role_primary TEXT,
  role_secondary TEXT,
  employment_type employment_type,
  employment_status employment_status NOT NULL DEFAULT 'active',
  hire_date DATE,
  termination_date DATE,
  termination_reason termination_reason,
  termination_notes TEXT,
  rehire_eligible BOOLEAN DEFAULT false,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_manager BOOLEAN NOT NULL DEFAULT false,
  can_approve_comps BOOLEAN NOT NULL DEFAULT false,
  can_approve_voids BOOLEAN NOT NULL DEFAULT false,
  last_shift_date DATE,
  last_incident_date DATE,
  toast_employee_id TEXT,
  toast_employee_guid TEXT,
  sevenshifts_employee_id TEXT,
  notes TEXT,
  additional_venues UUID[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE employee_profiles ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS venue_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  venue_id UUID UNIQUE NOT NULL REFERENCES venues(id),
  full_address TEXT,
  neighborhood TEXT,
  cross_streets TEXT,
  parking_situation TEXT,
  public_transit TEXT,
  delivery_instructions TEXT,
  google_maps_link TEXT,
  square_footage INTEGER,
  seating_capacity_indoor INTEGER,
  seating_capacity_outdoor INTEGER,
  bar_seats INTEGER,
  max_occupancy INTEGER,
  private_event_capacity INTEGER,
  num_tvs INTEGER,
  num_pos_terminals INTEGER,
  has_patio BOOLEAN DEFAULT false,
  has_stage BOOLEAN DEFAULT false,
  has_private_room BOOLEAN DEFAULT false,
  has_kitchen BOOLEAN DEFAULT false,
  kitchen_type TEXT,
  hours_monday TEXT,
  hours_tuesday TEXT,
  hours_wednesday TEXT,
  hours_thursday TEXT,
  hours_friday TEXT,
  hours_saturday TEXT,
  hours_sunday TEXT,
  happy_hour_times TEXT,
  brunch_hours TEXT,
  late_night_hours TEXT,
  kitchen_close_time TEXT,
  pos_system TEXT,
  scheduling_system TEXT,
  reservation_system TEXT,
  music_system TEXT,
  wifi_network TEXT,
  wifi_password TEXT,
  alarm_code TEXT,
  safe_combo TEXT,
  office_location TEXT,
  storage_location TEXT,
  walk_in_location TEXT,
  ice_machine_location TEXT,
  dumpster_location TEXT,
  electrical_panel_location TEXT,
  water_shutoff_location TEXT,
  gas_shutoff_location TEXT,
  liquor_license_number TEXT,
  liquor_license_expiry DATE,
  business_license_number TEXT,
  business_license_expiry DATE,
  health_permit_number TEXT,
  health_permit_expiry DATE,
  venue_description TEXT,
  quirks_and_notes TEXT,
  security_warning_flag TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE venue_profiles ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS venue_assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  venue_id UUID NOT NULL REFERENCES venues(id),
  role_at_venue TEXT NOT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT false,
  context staff_context,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, venue_id)
);
ALTER TABLE venue_assignments ENABLE ROW LEVEL SECURITY;

-- Backfill venue_assignments from user_bar_assignments
INSERT INTO venue_assignments (user_id, venue_id, role_at_venue, is_primary)
SELECT
  uba.user_id,
  v.id,
  COALESCE(ur.role::TEXT, 'staff'),
  true
FROM user_bar_assignments uba
JOIN venues v ON v.bar_code = uba.bar_id
LEFT JOIN user_roles ur ON ur.user_id = uba.user_id
ON CONFLICT (user_id, venue_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS employee_weekly_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id UUID NOT NULL REFERENCES employee_profiles(id),
  venue_id UUID NOT NULL REFERENCES venues(id),
  week_id UUID NOT NULL REFERENCES weeks(id),
  shifts_scheduled INTEGER,
  shifts_worked INTEGER,
  hours_scheduled DECIMAL(6,2),
  hours_worked DECIMAL(6,2),
  overtime_hours DECIMAL(6,2),
  late_arrivals INTEGER DEFAULT 0,
  late_minutes_total INTEGER DEFAULT 0,
  no_shows INTEGER DEFAULT 0,
  callouts INTEGER DEFAULT 0,
  break_violations INTEGER DEFAULT 0,
  net_sales DECIMAL(10,2),
  transactions INTEGER,
  tips_total DECIMAL(10,2),
  voids_count INTEGER DEFAULT 0,
  voids_amount DECIMAL(10,2),
  comps_count INTEGER DEFAULT 0,
  comps_amount DECIMAL(10,2),
  secret_shop_mention BOOLEAN DEFAULT false,
  secret_shop_score DECIMAL(5,2),
  secret_shop_notes TEXT,
  guest_complaints INTEGER DEFAULT 0,
  guest_compliments INTEGER DEFAULT 0,
  recognition_count INTEGER DEFAULT 0,
  coaching_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (employee_id, week_id)
);
ALTER TABLE employee_weekly_metrics ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS employee_certifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id UUID NOT NULL REFERENCES employee_profiles(id),
  cert_type TEXT,
  cert_name TEXT,
  cert_number TEXT,
  issuing_authority TEXT,
  issue_date DATE,
  expiration_date DATE,
  verified BOOLEAN DEFAULT false,
  verified_by TEXT,
  verified_date DATE,
  cert_document_url TEXT,
  renewal_reminder_sent BOOLEAN DEFAULT false,
  renewal_reminder_date DATE,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE employee_certifications ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS employee_incidents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id UUID NOT NULL REFERENCES employee_profiles(id),
  venue_id UUID NOT NULL REFERENCES venues(id),
  week_id UUID REFERENCES weeks(id),
  reported_by UUID NOT NULL,
  action_by UUID,
  incident_date DATE NOT NULL,
  incident_time TIME,
  incident_type incident_type NOT NULL,
  severity severity_level NOT NULL,
  description TEXT NOT NULL,
  witnesses TEXT,
  guests_involved BOOLEAN DEFAULT false,
  action_taken TEXT,
  action_type action_taken_type,
  follow_up_needed BOOLEAN DEFAULT false,
  follow_up_date DATE,
  resolved BOOLEAN DEFAULT false,
  outcome TEXT,
  related_incident_id UUID REFERENCES employee_incidents(id),
  ai_incident_summary TEXT,
  ai_severity_recommendation TEXT,
  ai_action_recommendation TEXT,
  ai_sentiment_analysis TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE employee_incidents ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS employee_reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id UUID NOT NULL REFERENCES employee_profiles(id),
  reviewer_id UUID NOT NULL,
  venue_id UUID NOT NULL REFERENCES venues(id),
  review_type review_type NOT NULL,
  review_date DATE NOT NULL,
  period_start DATE,
  period_end DATE,
  score_attendance SMALLINT,
  score_punctuality SMALLINT,
  score_job_knowledge SMALLINT,
  score_quality_of_work SMALLINT,
  score_productivity SMALLINT,
  score_teamwork SMALLINT,
  score_communication SMALLINT,
  score_customer_service SMALLINT,
  score_initiative SMALLINT,
  score_adaptability SMALLINT,
  overall_rating performance_rating,
  strengths TEXT,
  areas_for_improvement TEXT,
  goals_for_next_period TEXT,
  raise_recommended BOOLEAN DEFAULT false,
  promotion_recommended BOOLEAN DEFAULT false,
  pip_required BOOLEAN DEFAULT false,
  ai_summary TEXT,
  ai_development_recommendations TEXT,
  ai_review_sentiment TEXT,
  ai_performance_risk_level TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE employee_reviews ENABLE ROW LEVEL SECURITY;
